language: go
go:
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
before_deploy:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: [$(ls dist | awk 'BEGIN{ORS=","}{print$1}')]
  skip_cleanup: true
  on:
    branch: release
    tags: true
